### ISSUE TITLE
LG ThinQ: (LG ThinQ) 'onStart' failed 'EOFError':'EOF when reading a line'.

### ISSUE THREAD

**Issue by stingone** [majki09/domoticz_lg_thinq_plugin#1]
The V2 plugin worked perfect. however after a reinstall of domoticz it suddenly give me error below.

The script is working and detecting the AC.

2021-08-31 09:02:24.837 Error: LG ThinQ: (LG ThinQ) 'onStart' failed 'EOFError':'EOF when reading a line'.
2021-08-31 09:02:24.837 Error: LG ThinQ: (LG ThinQ) Exception traceback:
2021-08-31 09:02:24.837 Error: LG ThinQ: (LG ThinQ) ----> Line 383 in '/home/stingone/domoticz/plugins/domoticz_lg_thinq_plugin/plugin.py'
2021-08-31 09:02:24.837 Error: LG ThinQ: (LG ThinQ) ----> Line 115 in '/home/stingone/domoticz/plugins/domoticz_lg_thinq_plugin/plugin.py'
2021-08-31 09:02:24.837 Error: LG ThinQ: (LG ThinQ) ----> Line 254 in '/home/stingone/domoticz/plugins/domoticz_lg_thinq_plugin/example.py'
2021-08-31 09:02:24.837 Error: LG ThinQ: (LG ThinQ) ----> Line 27 in '/home/stingone/domoticz/plugins/domoticz_lg_thinq_plugin/example.py'

**Comment by majki09** [comment]
Thanks for reporting that. Are you sure you have valid _wideq_status.json_ file? It needs to be in **domoticz** folder (_/home/stingone/domoticz/wideq_status.json_ in your case).
I've recreated your problem with no _wideq_status.json_ and the result was very similar.
I've added checking of that file in last plugin update, please check it and let me know how it goes.

**Comment by Piefje01** [comment]
Then paste the URL where the browser is redirected:
https://kr.m.lgaccount.com/login/iabClose?state=bca5dfca53e011efa608b827eb049d9d&code=8QzmLZ7yBU5fi922euf0wWJbSYDTJl&user_number=NL2107100855927&oauth2_backend_url=https%3A%2F%2Fgb.lgeapi.com%2F
Traceback (most recent call last):
  File "example.py", line 423, in <module>
    main()
  File "example.py", line 419, in main
    ret = example(args.country, args.language, args.verbose, cmd=args.cmd, args=args.args)
  File "example.py", line 335, in example
    resp = example_command(client, cmd, args)
  File "example.py", line 283, in example_command
    return func(client, *args)
  File "example.py", line 59, in ls
    thinq1_devices = [dev for dev in client.devices if dev.platform_type == "thinq1"]
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/client.py", line 135, in devices
