### ISSUE TITLE
 Restart Plugin - issue presented again but no more usable 

### ISSUE THREAD

**Issue by sixzeroone** [majki09/domoticz_lg_thinq_plugin#16]
Hi Majki09,
same issue #15
no other changes or update in the infrastructure/devices on my side.
today I saw logs error continuosly and I had to disable both devices on DZ.

please have a look my error logs below:

```
2023-07-04 10:48:43.511 Error: AC Room1: Call to function 'onHeartbeat' failed, exception details:
2023-07-04 10:48:43.513 Error: AC Room1: Traceback (most recent call last):
2023-07-04 10:48:43.514 Error: AC Room1: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/plugin.py", line 341, in onHeartbeat
2023-07-04 10:48:43.514 Error: AC Room1: self.lg_device_status = self.lg_device.get_status()
2023-07-04 10:48:43.515 Error: AC Room1: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/ac.py", line 372, in get_status
2023-07-04 10:48:43.515 Error: AC Room1: res = self._get_deviceinfo_from_snapshot()
2023-07-04 10:48:43.516 Error: AC Room1: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/client.py", line 460, in _get_deviceinfo_from_snapshot
2023-07-04 10:48:43.516 Error: AC Room1: devices = self.client.session.get_devices()
2023-07-04 10:48:43.517 Error: AC Room1: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 525, in get_devices
2023-07-04 10:48:43.518 Error: AC Room1: return get_list(self.get("service/application/dashboard"), "item")
2023-07-04 10:48:43.518 Error: AC Room1: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 516, in get
2023-07-04 10:48:43.519 Error: AC Room1: language=self.auth.gateway.language,
2023-07-04 10:48:43.519 Error: AC Room1: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 281, in thinq_request
2023-07-04 10:48:43.520 Error: AC Room1: raise API_ERRORS[code](code)
2023-07-04 10:48:43.520 Error: AC Room1: wideq.core.NotLoggedInError: 0102
2023-07-04 10:48:43.521 Error: AC Room1:
2023-07-04 10:48:43.521 Error: AC Room1: During handling of the above exception, another exception occurred:
2023-07-04 10:48:43.522 Error: AC Room1:
2023-07-04 10:48:43.523 Error: AC Room1: Traceback (most recent call last):
2023-07-04 10:48:43.523 Error: AC Room1: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/plugin.py", line 578, in onHeartbeat
2023-07-04 10:48:43.524 Error: AC Room1: _plugin.onHeartbeat()
2023-07-04 10:48:43.524 Error: AC Room1: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/plugin.py", line 378, in onHeartbeat
2023-07-04 10:48:43.525 Error: AC Room1: self.lg_device = self.wideq_object.operate_device(device_id=self.DEVICE_ID)
2023-07-04 10:48:43.525 Error: AC Room1: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/plugin.py", line 745, in operate_device
2023-07-04 10:48:43.526 Error: AC Room1: lg_device = wideq.ACDevice(client, self._force_device(client, device_id))
2023-07-04 10:48:43.526 Error: AC Room1: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/plugin.py", line 726, in _force_device
2023-07-04 10:48:43.527 Error: AC Room1: device = client.get_device(device_id)
2023-07-04 10:48:43.528 Error: AC Room1: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/client.py", line 144, in get_device
2023-07-04 10:48:43.528 Error: AC Room1: for device in self.devices:
2023-07-04 10:48:43.528 Error: AC Room1: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/client.py", line 135, in devices
2023-07-04 10:48:43.528 Error: AC Room1: self._devices = self.session.get_devices()
2023-07-04 10:48:43.528 Error: AC Room1: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 525, in get_devices
2023-07-04 10:48:43.528 Error: AC Room1: return get_list(self.get("service/application/dashboard"), "item")
2023-07-04 10:48:43.528 Error: AC Room1: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 516, in get
2023-07-04 10:48:43.528 Error: AC Room1: language=self.auth.gateway.language,
2023-07-04 10:48:43.528 Error: AC Room1: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 281, in thinq_request
2023-07-04 10:48:43.528 Error: AC Room1: raise API_ERRORS[code](code)
2023-07-04 10:48:43.528 Error: AC Room1: wideq.core.AgreementError: 0110


2023-07-04 10:49:45.275 Error: AC Room2: Call to function 'onHeartbeat' failed, exception details:
2023-07-04 10:49:45.279 Error: AC Room2: Traceback (most recent call last):
2023-07-04 10:49:45.279 Error: AC Room2: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/plugin.py", line 341, in onHeartbeat
2023-07-04 10:49:45.279 Error: AC Room2: self.lg_device_status = self.lg_device.get_status()
2023-07-04 10:49:45.279 Error: AC Room2: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/ac.py", line 372, in get_status
2023-07-04 10:49:45.280 Error: AC Room2: res = self._get_deviceinfo_from_snapshot()
2023-07-04 10:49:45.280 Error: AC Room2: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/client.py", line 460, in _get_deviceinfo_from_snapshot
2023-07-04 10:49:45.280 Error: AC Room2: devices = self.client.session.get_devices()
2023-07-04 10:49:45.280 Error: AC Room2: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 525, in get_devices
2023-07-04 10:49:45.280 Error: AC Room2: return get_list(self.get("service/application/dashboard"), "item")
2023-07-04 10:49:45.280 Error: AC Room2: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 516, in get
2023-07-04 10:49:45.280 Error: AC Room2: language=self.auth.gateway.language,
2023-07-04 10:49:45.280 Error: AC Room2: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 281, in thinq_request
2023-07-04 10:49:45.280 Error: AC Room2: raise API_ERRORS[code](code)
2023-07-04 10:49:45.280 Error: AC Room2: wideq.core.NotLoggedInError: 0102
2023-07-04 10:49:45.281 Error: AC Room2:
2023-07-04 10:49:45.281 Error: AC Room2: During handling of the above exception, another exception occurred:
2023-07-04 10:49:45.281 Error: AC Room2:
2023-07-04 10:49:45.281 Error: AC Room2: Traceback (most recent call last):
2023-07-04 10:49:45.281 Error: AC Room2: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/plugin.py", line 578, in onHeartbeat
2023-07-04 10:49:45.281 Error: AC Room2: _plugin.onHeartbeat()
2023-07-04 10:49:45.281 Error: AC Room2: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/plugin.py", line 378, in onHeartbeat
2023-07-04 10:49:45.281 Error: AC Room2: self.lg_device = self.wideq_object.operate_device(device_id=self.DEVICE_ID)
2023-07-04 10:49:45.281 Error: AC Room2: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/plugin.py", line 745, in operate_device
2023-07-04 10:49:45.281 Error: AC Room2: lg_device = wideq.ACDevice(client, self._force_device(client, device_id))
2023-07-04 10:49:45.281 Error: AC Room2: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/plugin.py", line 726, in _force_device
2023-07-04 10:49:45.282 Error: AC Room2: device = client.get_device(device_id)
2023-07-04 10:49:45.282 Error: AC Room2: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/client.py", line 144, in get_device
2023-07-04 10:49:45.282 Error: AC Room2: for device in self.devices:
2023-07-04 10:49:45.282 Error: AC Room2: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/client.py", line 135, in devices
2023-07-04 10:49:45.282 Error: AC Room2: self._devices = self.session.get_devices()
2023-07-04 10:49:45.282 Error: AC Room2: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 525, in get_devices
2023-07-04 10:49:45.282 Error: AC Room2: return get_list(self.get("service/application/dashboard"), "item")
2023-07-04 10:49:45.282 Error: AC Room2: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 516, in get
2023-07-04 10:49:45.282 Error: AC Room2: language=self.auth.gateway.language,
2023-07-04 10:49:45.282 Error: AC Room2: File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 281, in thinq_request
2023-07-04 10:49:45.282 Error: AC Room2: raise API_ERRORS[code](code)
2023-07-04 10:49:45.282 Error: AC Room2: wideq.core.AgreementError: 0110 
```

I've already disabled and re-enabled them but no luck.
please are you able to something ?

currently is unusable

Regards

**Comment by sixzeroone** [comment]
Hi again,
I've just seen there is a new privacy change do be accepted on LG !

accepted it and now back everything online

**Comment by sixzeroone** [comment]
issue can be closed

**Comment by majki09** [comment]
> Hi again, I've just seen there is a new privacy change do be accepted on LG !
> 
> accepted it and now back everything online

This is what you should do. 
Thanks!
