### ISSUE TITLE
Reinstallation Failed

### ISSUE THREAD

**Issue by rnollen** [majki09/domoticz_lg_thinq_plugin#17]
Hi,

Everything was running perfectly since the last couple of days, but I needed to restart Domoticz today. Unfortunately the plugin stopped working after the restart. I have tried to reinstall it, so to start fresh, but I am not able to initialize the plugin. When executing the Example.py, I get the following error: 
```
Traceback (most recent call last):
  File "example.py", line 423, in <module>
    main()
  File "example.py", line 419, in main
    ret = example(args.country, args.language, args.verbose, cmd=args.cmd, args=args.args)
  File "example.py", line 335, in example
    resp = example_command(client, cmd, args)
  File "example.py", line 283, in example_command
    return func(client, *args)
  File "example.py", line 59, in ls
    thinq1_devices = [dev for dev in client.devices if dev.platform_type == "thinq1"]
  File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/client.py", line 135, in devices
    self._devices = self.session.get_devices()
  File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 525, in get_devices
    return get_list(self.get("service/application/dashboard"), "item")
  File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 510, in get
    return thinq_request(
  File "/home/<username>/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 281, in thinq_request
    raise API_ERRORS[code](code)
wideq.core.AgreementError: 0110
```

Any idea hat could cause this?

**Comment by majki09** [comment]
`wideq.core.AgreementError: 0110 `
means that you need to open LG app in your smartphone and accept new agreement. After that everything should work as before. It happens from time to time as LG introduces some changes in their agreements.

**Comment by rnollen** [comment]
@majki09 Awesome you're right. When performing the steps for example.py, I indeed got the new agreement questions, but it still didn't work afterwards when I did the reinstallation. I haven't opened the App though in that time..Accept the agreements in the App and everything was working afterwards; Thanks again!! So needed to do it there..
