### ISSUE TITLE
Errors log before and after last update

### ISSUE THREAD

**Issue by sixzeroone** [majki09/domoticz_lg_thinq_plugin#18]
Hello Majki09,
I got again errors on LG Ac devices, different errors before and after the last plugin update:

before the upgrade
`2023-09-11 01:49:48.362 Error: AC Room1: Call to function 'onHeartbeat' failed, exception details:
2023-09-11 01:49:48.363 Error: AC Room1: Traceback (most recent call last):
2023-09-11 01:49:48.363 Error: AC Room1: File "/home/marco/domoticz/plugins/domoticz_lg_thinq_plugin/plugin.py", line 578, in onHeartbeat
2023-09-11 01:49:48.363 Error: AC Room1: _plugin.onHeartbeat()
2023-09-11 01:49:48.363 Error: AC Room1: File "/home/marco/domoticz/plugins/domoticz_lg_thinq_plugin/plugin.py", line 341, in onHeartbeat
2023-09-11 01:49:48.363 Error: AC Room1: self.lg_device_status = self.lg_device.get_status()
2023-09-11 01:49:48.363 Error: AC Room1: File "/home/marco/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/ac.py", line 372, in get_status
2023-09-11 01:49:48.363 Error: AC Room1: res = self._get_deviceinfo_from_snapshot()
2023-09-11 01:49:48.363 Error: AC Room1: File "/home/marco/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/client.py", line 460, in _get_deviceinfo_from_snapshot
2023-09-11 01:49:48.363 Error: AC Room1: devices = self.client.session.get_devices()
2023-09-11 01:49:48.363 Error: AC Room1: File "/home/marco/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 525, in get_devices
2023-09-11 01:49:48.363 Error: AC Room1: return get_list(self.get("service/application/dashboard"), "item")
2023-09-11 01:49:48.363 Error: AC Room1: File "/home/marco/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 516, in get
2023-09-11 01:49:48.363 Error: AC Room1: language=self.auth.gateway.language,
2023-09-11 01:49:48.363 Error: AC Room1: File "/home/marco/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 283, in thinq_request
2023-09-11 01:49:48.363 Error: AC Room1: raise APIError(code)
2023-09-11 01:49:48.364 Error: AC Room1: wideq.core.APIError: 9995 `

After plugin update:
`2023-09-20 14:00:09.232 Error: AC Room1: Call to function 'onHeartbeat' failed, exception details:
2023-09-20 14:00:09.237 Error: AC Room1: Traceback (most recent call last):
2023-09-20 14:00:09.238 Error: AC Room1: File "/home/marco/domoticz/plugins/domoticz_lg_thinq_plugin/plugin.py", line 578, in onHeartbeat
2023-09-20 14:00:09.238 Error: AC Room1: _plugin.onHeartbeat()
2023-09-20 14:00:09.238 Error: AC Room1: File "/home/marco/domoticz/plugins/domoticz_lg_thinq_plugin/plugin.py", line 341, in onHeartbeat
2023-09-20 14:00:09.238 Error: AC Room1: self.lg_device_status = self.lg_device.get_status()
2023-09-20 14:00:09.238 Error: AC Room1: File "/home/marco/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/ac.py", line 372, in get_status
2023-09-20 14:00:09.238 Error: AC Room1: res = self._get_deviceinfo_from_snapshot()
2023-09-20 14:00:09.238 Error: AC Room1: File "/home/marco/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/client.py", line 460, in _get_deviceinfo_from_snapshot
2023-09-20 14:00:09.238 Error: AC Room1: devices = self.client.session.get_devices()
2023-09-20 14:00:09.238 Error: AC Room1: File "/home/marco/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 526, in get_devices
2023-09-20 14:00:09.238 Error: AC Room1: return get_list(self.get("service/application/dashboard"), "item")
2023-09-20 14:00:09.238 Error: AC Room1: File "/home/marco/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 517, in get
2023-09-20 14:00:09.238 Error: AC Room1: language=self.auth.gateway.language,
2023-09-20 14:00:09.238 Error: AC Room1: File "/home/marco/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 284, in thinq_request
2023-09-20 14:00:09.238 Error: AC Room1: raise APIError(code)
2023-09-20 14:00:09.238 Error: AC Room1: wideq.core.APIError: 9999 `

devices works anyway, but I have huge spam of logs in the error page

could you fix it ?

Regards

**Comment by majki09** [comment]
Hi @sixzeroone.
There was no updates since last commit, which looks fine. I assume you did `git pull --rebase`
These errors are pointing to some issues with LG API. What model is your AC?
Have you tried reinstalling (with generating the _wideq_ file again) the plugin?

**Comment by sixzeroone** [comment]
Hello @majki09 ,
did you had chance to check these logs error ?

**Comment by sixzeroone** [comment]
Hi @majki09 
I had to disable this plugin untill you fix it, otherwise it's spamming tons of logs .
please let me know what you can do in order to fix it.
