### ISSUE TITLE
lg-wh27s

### ISSUE THREAD

**Issue by marcelv73** [majki09/domoticz_lg_thinq_plugin#19]
Hi, got an lg-wh27s heatpumpboiler

it seems not to be recognised ; will this be supported in future ?

thinq2 devices: 1
ValueError: 406 is not a valid DeviceType

**Comment by PvdGulik** [comment]
I do have wh27s. Which information do you need. I'm willing to help.

Thanks!

**Comment by PvdGulik** [comment]
Trying to run the script with two devices, I get this result:

```
pi@Domoticz:~/domoticz/plugins/domoticz_lg_thinq_plugin $ python3 example.py -c NL -l nl-NL
2024-06-01 12:20:11 ERROR [wideq.example] wideq_state file not found. Trying to load default STATE_FILE: wideq_state.json
2024-06-01 12:20:11 INFO [wideq.example] wideq_state will be loaded from: wideq_state.json
2024-06-01 12:20:11 INFO [wideq.example] State data loaded from /home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/wideq_state.json'

thinq2 devices: 2
Traceback (most recent call last):
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 423, in <module>
    main()
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 419, in main
    ret = example(args.country, args.language, args.verbose, cmd=args.cmd, args=args.args)
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 335, in example
    resp = example_command(client, cmd, args)
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 283, in example_command
    return func(client, *args)
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 71, in ls
    print("{0.id}: {0.name} ({0.type.name} {0.model_id} / {0.platform_type})".format(device))
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/client.py", line 317, in type
    return DeviceType(self.data["deviceType"])
  File "/usr/lib/python3.9/enum.py", line 360, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.9/enum.py", line 677, in __new__
    raise ve_exc
ValueError: 406 is not a valid DeviceType
```

What to do?
