### ISSUE TITLE
get_list TypeError: string indices must be integers, not 'str'

### ISSUE THREAD

**Issue by Luckymr2201** [majki09/domoticz_lg_thinq_plugin#21]
Hello,

I am using this plugin for some time but needed to clear everything and start from scratch on my new Pi5.
I installed the plugin and attempted to register running the example as below (being located in France):

pi@Pie5B:~/domoticz/plugins/domoticz_lg_thinq_plugin $ sudo python3 example.py -c FR -l fr-FR

I am getting requested to login to my LG account using the URL:

2024-07-26 09:46:58 ERROR [wideq.example] wideq_state file not found. Trying to load default STATE_FILE: wideq_state.json
2024-07-26 09:46:58 INFO [wideq.example] wideq_state will be loaded from: wideq_state.json
2024-07-26 09:46:58 ERROR [wideq.example] No state file found (tried: '/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/wideq_state.json')
Log in here:
https://fr.m.lgaccount.com/spx/login/signIn?country=FR&language=fr-FR&svc_list=SVC202&client_id=LGAO221A02&division=ha&redirect_uri=https%3A%2F%2Fkr.m.lgaccount.com%2Flogin%2FiabClose&state=Z%2CFBK
Then paste the URL where the browser is redirected:

I logon and get the URL needed that I paste:

https://kr.m.lgaccount.com/login/iabClose?state=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&code=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&user_number=xxxxxxxxxxxxxxxxxxx&oauth2_backend_url=https%3A%2F%2Fgb.lgeapi.co

but then it goes south:

Traceback (most recent call last):
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 423, in <module>
    main()
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 419, in main
    ret = example(args.country, args.language, args.verbose, cmd=args.cmd, args=args.args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 335, in example
    resp = example_command(client, cmd, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 283, in example_command
    return func(client, *args)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 59, in ls
    thinq1_devices = [dev for dev in client.devices if dev.platform_type == "thinq1"]
                                     ^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/client.py", line 135, in devices
    self._devices = self.session.get_devices()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 526, in get_devices
    return get_list(self.get("service/application/dashboard"), "item")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 142, in get_list
    val = obj[key]
          ~~~^^^^^
TypeError: string indices must be integers, not 'str'

I am not developer but Googled this and it seems to be a "fair" complaint.  I just do not know why nobody else would have faced this before. 
Can you tell me if I am doing anything wrong ?

Thank you.

**Comment by majki09** [comment]
Hi @Luckymr2201 !
1. Do you for any chance have your old `wideq_state.json`? You could use it for new instance.
2. Recently LG updated agrements that every user need to accept with official mobile app. Did you accept it already?

**Comment by Luckymr2201** [comment]
Hi @majki09 , thank you for your reply. Yes, I have run the mobile application and can control all my AC with it and also I accepted latest terms and conditions. 
I also retrieved an old wideq_state.json file and used again exemple.py to get my list of identifiers but I get the same error message.
My last attempt was to restore the wideq_state.json in the plugin folder and place it back in the root of domoticz then added an hardwae for one of the heatpumps module. Here is what I get from the domoticz logs:

2024-07-29 11:18:58.489 PAC_Chambre_Babette: Could NOT log in. Probably you need to accept new agreement in the mobile app.
2024-07-29 11:18:58.619 PAC_Chambre_Babette: Could NOT log in. Probably you need to accept new agreement in the mobile app.
2024-07-29 11:18:58.756 PAC_Chambre_Babette: Could NOT log in. Probably you need to accept new agreement in the mobile app.
2024-07-29 11:18:58.889 PAC_Chambre_Babette: Could NOT log in. Probably you need to accept new agreement in the mobile app.

**Comment by Luckymr2201** [comment]
Additional tests I just made:
1- Removed wideq_state.json file from root of Domoticz and restarted Domoticz service; I get those messages in loop:
2024-07-29 11:34:39.043 PAC_Chambre_Babette: Pushing 'onHeartbeatCallback' on to queue
2024-07-29 11:34:39.093 PAC_Chambre_Babette: Processing 'onHeartbeatCallback' message
2024-07-29 11:34:39.093 PAC_Chambre_Babette: Acquiring GIL for 'onHeartbeatCallback'
2024-07-29 11:34:39.093 PAC_Chambre_Babette: Calling message handler 'onHeartbeat' on 'module' type object.
2024-07-29 11:34:39.093 PAC_Chambre_Babette: Acquiring GIL for 'onHeartbeatCallback'
2- Edited wideq_state.json and changed access token, refresh token and user number to put wrong values on purpose then restarted Domoticz service. I get also same messages.

So this tells me the file wideq_state.json seems OK. I have no idea what is going wrong here.

**Comment by majki09** [comment]
1. How many LG devices are you using in your domoticz?
2. Please put a screenshot of Hardware tab with LG devices in your domoticz.
3. Please try `-c FR -l en-US` when logging to LG.
4. Can you put here the output of point no. 2 of [Installation](https://github.com/majki09/domoticz_lg_thinq_plugin?tab=readme-ov-file#installation) section from the manual.

**Comment by Luckymr2201** [comment]
Hello, 

1. I have 4 AC modules which are considered as v1 and 4 AC modules of newer generation which are v2
2. Screen shot attached (hardware.jpeg)
![Hardware](https://github.com/user-attachments/assets/286e809d-6370-4023-8e34-aa01612a8fce)
4. I tried to change in the hardware language by "en-US" and restarted Domoticz service: same result. 
5. Here is the output requested:

pi@Pie5B:~/domoticz/plugins/domoticz_lg_thinq_plugin $ sudo python3 example.py -c FR -l en-US
2024-07-31 13:09:20 ERROR [wideq.example] wideq_state file not found. Trying to load default STATE_FILE: wideq_state.json
2024-07-31 13:09:20 INFO [wideq.example] wideq_state will be loaded from: wideq_state.json
2024-07-31 13:09:20 ERROR [wideq.example] No state file found (tried: '/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/wideq_state.json')
Log in here:
https://fr.m.lgaccount.com/spx/login/signIn?country=FR&language=en-US&svc_list=SVC202&client_id=LGAO221A02&division=ha&redirect_uri=https%3A%2F%2Fkr.m.lgaccount.com%2Flogin%2FiabClose&state=55b61e9a4f2d11efb7b1d83adde12759&show_thirdparty_login=AMZ%2CFBK
Then paste the URL where the browser is redirected:
https://kr.m.lgaccount.com/login/iabClose?state=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&code=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&user_number=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&oauth2_backend_url=https%3A%2F%2Fgb.lgeapi.com%2F
Traceback (most recent call last):
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 423, in <module>
    main()
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 419, in main
    ret = example(args.country, args.language, args.verbose, cmd=args.cmd, args=args.args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 335, in example
    resp = example_command(client, cmd, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 283, in example_command
    return func(client, *args)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 59, in ls
    thinq1_devices = [dev for dev in client.devices if dev.platform_type == "thinq1"]
                                     ^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/client.py", line 135, in devices
    self._devices = self.session.get_devices()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 526, in get_devices
    return get_list(self.get("service/application/dashboard"), "item")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line 142, in get_list
    val = obj[key]
          ~~~^^^^^
TypeError: string indices must be integers, not 'str'

Let me know if anything is missing

**Comment by Piefje01** [comment]
Same thing here.

**Comment by majki09** [comment]
Forgot to ask about the obvious thing. Please make sure you all use the latest release of the plugin by executing
`git pull`
Also, I've noticed that 'wideq' plugin stopped working for some people. I need to investigate it, but please give me some time, because it's vacation season.

**Comment by Luckymr2201** [comment]
Hello @majki09,

Thank you for helping us with this.

To be certain I was doing things right I completely deleted the "domoticz_lg_thinq_plugin" from plugins, then reinstalled it using your instructions but this does not change the outcome. The error message clearly comes from the core.py which is definately wideq.

Let me know if you need any more test and enjoy your vacations.

**Comment by majki09** [comment]
Hi @Luckymr2201 and @Piefje01.
Try out the new version https://github.com/majki09/domoticz_lg_thinq_plugin/releases/tag/v2.2.2 (or just `git pull`)

Just asking: do you have any Thinq V1 devices on your accounts? I do not (I have only V2 Air Conditioner) and it was working fine before. I think there was a problem with fetching V1 devices from LG servers, but let's see if it's working for you now.

**Comment by Luckymr2201** [comment]
Hi @majki09,

I deleted entirely once again the plugin folder then imported it again.
I have run again the commands and I still get the exact same error:

pi@Pie5B:~/domoticz/plugins/domoticz_lg_thinq_plugin $ python3 example.py -c FR                                     -l fr-FR
2024-08-22 07:45:55 ERROR [wideq.example] wideq_state file not found. Trying to                                     load default STATE_FILE: wideq_state.json
2024-08-22 07:45:55 INFO [wideq.example] wideq_state will be loaded from: wideq_                                    state.json
2024-08-22 07:45:55 ERROR [wideq.example] No state file found (tried: '/home/pi/                                    domoticz/plugins/domoticz_lg_thinq_plugin/wideq_state.json')
Log in here:
https://fr.m.lgaccount.com/spx/login/signIn?country=FR&language=fr-FR&svc_list=S                                    VC202&client_id=LGAO221A02&division=ha&redirect_uri=https%3A%2F%2Fkr.m.lgaccount                                    .com%2Flogin%2FiabClose&state=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&show_thirdparty_l                                    ogin=AMZ%2CFBK
Then paste the URL where the browser is redirected:
https://kr.m.lgaccount.com/login/iabClose?state=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&code=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&user_number=xxxxxxxxxxxxxxxxxx&oauth2_backend_                                    url=https%3A%2F%2Fgb.lgeapi.com%2F
No thinq1 devices found or there was some LG server error.
Traceback (most recent call last):
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 427                                    , in <module>
    main()
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 423                                    , in main
    ret = example(args.country, args.language, args.verbose, cmd=args.cmd, args=                                    args.args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                    ^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 339                                    , in example
    resp = example_command(client, cmd, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 287                                    , in example_command
    return func(client, *args)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 70,                                     in ls
    thinq2_devices = [dev for dev in client.devices if dev.platform_type == "thi                                    nq2"]
                                     ^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/client.py", lin                                    e 135, in devices
    self._devices = self.session.get_devices()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line                                     526, in get_devices
    return get_list(self.get("service/application/dashboard"), "item")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/core.py", line                                     142, in get_list
    val = obj[key]
          ~~~^^^^^
TypeError: string indices must be integers, not 'str'

Well when I say same error, indeed exception is not raised for thing1 command but for thinq2.

I confirm though I have a mix of thinq1 and thing2 devices on my LG account.

Forgive my developer skills ignorance but the error message seems "fair" to me. How can we ask a value to be extracted from a array not using an integer value but instead using a string ?

Once again thank you for your support with this because I only realize since I lost control of my AC modules how much I depend on this system.

**Comment by Piefje01** [comment]
TypeError: string indices must be integers

**Comment by Piefje01** [comment]
sudo python3 example.py -c NL -l en-US
2024-08-22 11:26:45 ERROR [wideq.example] wideq_state file not found. Trying to load default STATE_FILE: wideq_state.json
2024-08-22 11:26:45 INFO [wideq.example] wideq_state will be loaded from: wideq_state.json
2024-08-22 11:26:45 ERROR [wideq.example] No state file found (tried: '/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/wideq_state.json')

**Comment by Piefje01** [comment]
Traceback (most recent call last):
  File "example.py", line 214, in <module>
    example(sys.argv[1:])
  File "example.py", line 200, in example
    example_command(client, args)
  File "example.py", line 177, in example_command
    ls(client)
  File "example.py", line 25, in ls
    for device in client.devices:
  File "/home/pi/LGAC_SmartT/wideq.py", line 474, in devices
    self._devices = self.session.get_devices()
  File "/home/pi/LGAC_SmartT/wideq.py", line 465, in session
    self._session, self._devices = self.auth.start_session()
  File "/home/pi/LGAC_SmartT/wideq.py", line 257, in start_session
    return Session(self, session_id), as_list(session_info['item'])
KeyError: 'item'

**Comment by Piefje01** [comment]
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian

**Comment by majki09** [comment]
Hi @Luckymr2201.

> Forgive my developer skills ignorance but the error message seems "fair" to me. How can we ask a value to be extracted from a array not using an integer value but instead using a string ?

We cannot do this in Python, that's why it's raising an error. Here the reason could be just an empty array. I want to find out why it's happening.

@Luckymr2201, @Piefje01 are you able to share with me your `wideq_state.json` file? As I own only V2 LG device it's impossible for me to reflect your setup with V1 devices.

**Comment by Luckymr2201** [comment]
@majki09, it does not seems very safe to publish actual data here that could be used to gain access to my system (I am sure you will understand this concern). Is there some logging you would want me to add to any of the code to attempt retrieving that flow of data I am getting from the server ? I am happy to test anything you feel is needed. I do not know either where you are located but we could imagine a remote share session where you could see my laptop. I am located in France (well the command to access LG server probably gave me away on this :)). Is there a way to exchange privately ? I did not see any option here. Thanks.

**Comment by Luckymr2201** [comment]
Hello @majki09 let me know how I can share with you my access so you can test and hopefully resolve this. As they say in game of throne : the winter is coming 😊😊

**Comment by Luckymr2201** [comment]
Hello @majki09 , desperate times, desperates measures. I created a second LG account and I moved to this new account only my v2 devices. This works. So I am ending up with 2 accounts : 1 to hold and manage my v1 devices using a legacy plugin which still works and a second account only for v2 devices. This seems to do the trick (I get domoticz controling them properly. 

@Piefje01, if you get desperate I suggest you do the same.  I hope this trick will help others in case they ever face the same problem.

**Comment by majki09** [comment]
Hi @Luckymr2201. You can use whatever way you want to share the wideq file with me. In the past one colleague shared this file with me via domoticz forum PM and I've got from him a link via some site like mega.com. You can even encrypt this file with a password if you want before.

My domoticz forum nickname is 'majki'.

**Comment by Luckymr2201** [comment]
Hi @majki09 , I already moved all my v2 devices to a second account I created and your plugin works perfectly well now. It will only be difficult if I ever want to use the mobile phone app but Domoticz is my main requirement so I think I will leave it like this. Thank you for your support

**Comment by majki09** [comment]
I'm glad that you found it out and it works fine for you. I will close this issue then.

**Comment by Piefje01** [comment]
Hi, i realy dont know whate you mean with v2.  How do i know if lg is a v2 device.
