### ISSUE TITLE
After upgrade to Bookworm, Error: LG ThinQ WP: wideq_state file not found!

### ISSUE THREAD

**Issue by PvdGulik** [majki09/domoticz_lg_thinq_plugin#24]
2024-12-14 23:39:34.700 Status: LG ThinQ WP: Entering work loop.
2024-12-14 23:39:34.701 LG ThinQ WP: Worker thread started.
2024-12-14 23:39:34.701 Status: LG ThinQ WP: Started.
2024-12-14 23:39:35.688 Status: LG ThinQ WP: Initialized version 2.2.2, author 'majki'
2024-12-14 23:39:35.696 Error: LG ThinQ WP: wideq_state file not found!

**Comment by PvdGulik** [comment]
2024-12-14 23:39:35.696 Error: LG ThinQ WP: wideq_state file not found! 
Tried: [(https://github.com/majki09/domoticz_lg_thinq_plugin/issues/7)]

which end in while registering:

`
Traceback (most recent call last):
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 427, in <module>
    main()
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 423, in main
    ret = example(args.country, args.language, args.verbose, cmd=args.cmd, args=args.args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 339, in example
    resp = example_command(client, cmd, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 287, in example_command
    return func(client, *args)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 75, in ls
    print("{0.id}: {0.name} ({0.type.name} {0.model_id} / {0.platform_type})".format(device))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/client.py", line 317, in type
    return DeviceType(self.data["deviceType"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 717, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 1133, in __new__
    raise ve_exc
ValueError: 406 is not a valid DeviceType
`

And in domoticz log:

`
2024-12-16 19:54:30.133 LG ThinQ WP: Worker thread started.
2024-12-16 19:54:30.132 Status: LG ThinQ WP: Entering work loop.
2024-12-16 19:54:30.133 Status: LG ThinQ WP: Started.
2024-12-16 19:54:31.082 Status: LG ThinQ WP: Initialized version 2.2.2, author 'majki'
2024-12-16 19:54:31.090 LG ThinQ WP: wideq_state file found in non-docker location.
2024-12-16 19:54:31.091 LG ThinQ WP: State data loaded from '/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/wideq_state.json'
2024-12-16 19:54:32.097 Error: LG ThinQ WP: Call to function 'onStart' failed, exception details:
2024-12-16 19:54:32.113 Error: LG ThinQ WP: Traceback (most recent call last):
2024-12-16 19:54:32.113 Error: LG ThinQ WP: File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/plugin.py", line 554, in onStart
2024-12-16 19:54:32.113 Error: LG ThinQ WP: _plugin.onStart()
2024-12-16 19:54:32.113 Error: LG ThinQ WP: File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/plugin.py", line 107, in onStart
2024-12-16 19:54:32.113 Error: LG ThinQ WP: self.lg_device = self.wideq_object.operate_device(device_id=self.DEVICE_ID)
2024-12-16 19:54:32.113 Error: LG ThinQ WP: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-16 19:54:32.113 Error: LG ThinQ WP: File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/plugin.py", line 740, in operate_device
2024-12-16 19:54:32.113 Error: LG ThinQ WP: client._auth = self.authenticate(client.gateway)
2024-12-16 19:54:32.113 Error: LG ThinQ WP: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-16 19:54:32.113 Error: LG ThinQ WP: File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/plugin.py", line 712, in authenticate
2024-12-16 19:54:32.113 Error: LG ThinQ WP: callback_url = input()
2024-12-16 19:54:32.113 Error: LG ThinQ WP: ^^^^^^^
2024-12-16 19:54:32.113 Error: LG ThinQ WP: EOFError: EOF when reading a line
2024-12-16 19:59:12.723 Status: [web:8080] Incoming connection from: 192.168.1.111
2024-12-16 20:00:01.429 Status: Notification: Battery Low: Garage voordeur (Level: Low)
`

System info:
Version: 2024.7
Build Hash: b317cfab1
Compile Date: 2024-07-13 16:59:31
dzVents Version: 3.1.8
Python Version: 3.11.2 (main, Sep 14 2024, 03:00:30) [GCC 12.2.0]

**Comment by ajongen** [comment]
I had the same problem. What I did was replicate the hardware in the hardware page by selecting the old Airco and click Add. This recreates the airco. Then I deleted the old hardware instance. This solved the problem for me. Maybe this solves your problem too.

**Comment by PvdGulik** [comment]
Thanks, but sadly it did not solve my problem...

```
2024-12-27 15:13:37.928 LG ThinQ WP: Worker thread started.
2024-12-27 15:13:37.928 Status: LG ThinQ WP: Entering work loop.
2024-12-27 15:13:37.928 Status: LG ThinQ WP: Started.
2024-12-27 15:13:39.770 Status: LG ThinQ WP: Initialized version 2.2.2, author 'majki'
2024-12-27 15:13:39.773 Error: LG ThinQ WP: wideq_state file not found!
```

**Comment by PvdGulik** [comment]
I completly removed the plugin and started all over, but still no result.:

```
pi@Domoticz:~/domoticz/plugins/domoticz_lg_thinq_plugin $ python3 example.py -c NL -l en-US
2024-12-28 18:38:22 ERROR [wideq.example] wideq_state file not found. Trying to load default STATE_FILE: wideq_state.json
2024-12-28 18:38:22 INFO [wideq.example] wideq_state will be loaded from: wideq_state.json
2024-12-28 18:38:22 ERROR [wideq.example] No state file found (tried: '/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/wideq_state.json')
Log in here:
https://nl.m.lgaccount.com/spx/login/signIn?country=NL&language=en-US&svc_list=SVC202&client_id=LGAOXXXXXXX&division=ha&redirect_uri=https%3A%2F%2Fkr.m.lgaccount.com%2Flogin%2FiabClose&state=89514028c54211ef911cb827eXXXXXXXX&show_thirdparty_login=AMZXXXXXX
Then paste the URL where the browser is redirected:
https://kr.m.lgaccount.com/login/iabClose?state=89514028c54211ef911cb827ebe2XXXXXXX&code=0frGUgPzX8fxwUIzoyzdqKrHNXXXXXX&user_number=NL190810XXXXXX&oauth2_backend_url=https%3A%2F%2Fgb.lgeapi.com%2F

thinq2 devices: 2
75b21e19-0b3b-1424-886b-b8165XXXXXX: Lucht-water H/P (AC AWHP_019101_WW / thinq2)
Traceback (most recent call last):
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 427, in <module>
    main()
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 423, in main
    ret = example(args.country, args.language, args.verbose, cmd=args.cmd, args=args.args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 339, in example
    resp = example_command(client, cmd, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 287, in example_command
    return func(client, *args)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 75, in ls
    print("{0.id}: {0.name} ({0.type.name} {0.model_id} / {0.platform_type})".format(device))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/client.py", line 317, in type
    return DeviceType(self.data["deviceType"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 717, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 1133, in __new__
    raise ve_exc
ValueError: 406 is not a valid DeviceType

```

Please help, don't know what else to do...

**Comment by majki09** [comment]
`ValueError: 406 is not a valid DeviceType`

It seems that your device is not yet supported by the plugin or LG has changed something in their API.

What kind of device you are trying to add to domoticz? Is it air conditioner?

**Comment by PvdGulik** [comment]
Your plugin worked with the two devices, only after upgrading tot Bookworm it stopped working.
I have two devices:

1.  AirWaterHeatPump (AWHP), type HM093MR.U44, which always worked in Domoticz.
2. HeatPumpBolier, type WH27S, which is not supported in your plug-in, see https://github.com/majki09/domoticz_lg_thinq_plugin/issues/19

Even with the not supported WH27S, the AWHP was working till the upgrade to Bookworm.

Both devices are working in HomeAssistant with the plugin https://github.com/ollo69/ha-smartthinq-sensors
And the AWHP is also working in HomeBridge with the plugin https://github.com/nVuln/homebridge-lg-thinq

So I don't understand why I can't it running anymore in Domoticz under Bookworm.

Thanks!

**Comment by majki09** [comment]
Hi @PvdGulik 
Currently I don't have enough free time to look on this. I have sent you an e-mail. Let me know what you think. Thanks!

**Comment by PvdGulik** [comment]
Hello majki09,

I missed your mail, I think your mail ended in my spam-folder, and is it deleted automatically.
Can you please send it again, because the problem is still there.

Thanks!

**Comment by PvdGulik** [comment]
Thought I'll try it again after a year, but stil have the same issue. Don't know how to solve. Any help is appreciated.

```
pi@Domoticz:~/domoticz/plugins/domoticz_lg_thinq_plugin $ python3 example.py -c NL -l nl-NL
2025-12-29 15:29:38 ERROR [wideq.example] wideq_state file not found. Trying to load default STATE_FILE: wideq_state.json
2025-12-29 15:29:38 INFO [wideq.example] wideq_state will be loaded from: wideq_state.json
2025-12-29 15:29:38 ERROR [wideq.example] No state file found (tried: '/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/wideq_state.json')
Log in here:
https://nl.m.lgaccount.com/spx/login/signIn?country=NL&language=nl-NL&svc_list=SVC202&client_id=LGAO221A02&division=ha&redirect_uri=https%3A%2F%2Fkr.m.lgaccount.com%2Flogin%2FiabClose&state=cea02a2ce4c211******be28a52&show_thirdparty_login=AMZ%2CFBK
Then paste the URL where the browser is redirected:
https://kr.m.lgaccount.com/login/iabClose?state=cea02a2ce4c2********be28a52&code=WiFg7iehPZ6AT*******TeQSx4GY&user_number=NL1908*******16&oauth2_backend_url=https%3A%2F%2Fgb.lgeapi.com%2F

thinq2 devices: 2
75b21e19-0b3b-1424-886b-b816*******8: Lucht-water H/P (AC AWHP_019101_WW / thinq2)
Traceback (most recent call last):
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 427, in <module>
    main()
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 423, in main
    ret = example(args.country, args.language, args.verbose, cmd=args.cmd, args=args.args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 339, in example
    resp = example_command(client, cmd, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 287, in example_command
    return func(client, *args)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/example.py", line 75, in ls
    print("{0.id}: {0.name} ({0.type.name} {0.model_id} / {0.platform_type})".format(device))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/client.py", line 317, in type
    return DeviceType(self.data["deviceType"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 717, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 1133, in __new__
    raise ve_exc
ValueError: 406 is not a valid DeviceType
pi@Domoticz:~/domoticz/plugins/domoticz_lg_thinq_plugin $ sudo systemctl restart domoticz.service
pi@Domoticz:~/domoticz/plugins/domoticz_lg_thinq_plugin $ ls -l
total 172
-rw-r--r-- 1 pi   pi   86326 Mar 12  2025 domoticz.jpg
-rw-r--r-- 1 pi   pi   11238 Mar 12  2025 energy_history2domoticz.py
-rw-r--r-- 1 pi   pi   13680 Mar 12  2025 example.py
-rw-r--r-- 1 pi   pi    1075 Mar 12  2025 LICENSE
-rw-r--r-- 1 pi   pi   33743 Mar 12  2025 plugin.py
drwxr-x--- 2 root root  4096 Mar 12  2025 __pycache__
-rw-r--r-- 1 pi   pi    6188 Mar 12  2025 README.md
drwxr-xr-x 3 pi   pi    4096 Mar 12  2025 wideq
pi@Domoticz:~/domoticz/plugins/domoticz_lg_thinq_plugin $ ls wideq_state.json
ls: cannot access 'wideq_state.json': No such file or directory
pi@Domoticz:~/domoticz/plugins/domoticz_lg_thinq_plugin $ sudo systemctl restart domoticz.service
pi@Domoticz:~/domoticz/plugins/domoticz_lg_thinq_plugin $ ls -l
total 172
-rw-r--r-- 1 pi   pi   86326 Mar 12  2025 domoticz.jpg
-rw-r--r-- 1 pi   pi   11238 Mar 12  2025 energy_history2domoticz.py
-rw-r--r-- 1 pi   pi   13680 Mar 12  2025 example.py
-rw-r--r-- 1 pi   pi    1075 Mar 12  2025 LICENSE
-rw-r--r-- 1 pi   pi   33743 Mar 12  2025 plugin.py
drwxr-x--- 2 root root  4096 Mar 12  2025 __pycache__
-rw-r--r-- 1 pi   pi    6188 Mar 12  2025 README.md
drwxr-xr-x 3 pi   pi    4096 Mar 12  2025 wideq
pi@Domoticz:~/domoticz/plugins/domoticz_lg_thinq_plugin $ 
```

Domoticz Log:

```
2025-12-29 15:32:26.578 Status: LG ThinQ WP: Entering work loop.
2025-12-29 15:32:26.578 LG ThinQ WP: Worker thread started.
2025-12-29 15:32:26.578 Status: LG ThinQ WP: Started.
2025-12-29 15:32:27.632 Status: LG ThinQ WP: Initialized version 2.2.2, author 'majki'
2025-12-29 15:32:27.638 Error: LG ThinQ WP: wideq_state file not found!
2025-12-29 15:33:23.758 Status: LG ThinQ WP: Stop directive received.
2025-12-29 15:33:23.758 LG ThinQ WP: onStop called
2025-12-29 15:33:23.871 Status: LG ThinQ WP: Exiting work loop.
2025-12-29 15:33:23.958 Status: LG ThinQ WP: Stopping threads.
2025-12-29 15:33:23.959 Status: LG ThinQ WP: Stopped.
2025-12-29 15:32:27.638 Error: LG ThinQ WP: wideq_state file not found!
```

**Comment by PvdGulik** [comment]
Problem solved with help op Gemini!:


```
De reden is simpel: LG heeft nieuwe apparaatcodes toegevoegd (jouw Warmtepomp heeft code 406), maar de library in de plugin kent die code nog niet. Hij crasht omdat hij niet weet wat een "406" is.

De Oplossing: De DeviceType handmatig toevoegen
We gaan de code van de plugin een klein beetje aanpassen zodat hij code 406 herkent als een geldig apparaat.

Open het bestand waar de apparaattypes staan:

Bash
nano ~/domoticz/plugins/domoticz_lg_thinq_plugin/wideq/client.py
Zoek de lijst met DeviceType (gebruik Ctrl+W en typ class DeviceType): Je ziet daar een lijst met namen en nummers, zoals:

Python
class DeviceType(Enum):
    REFRIGERATOR = 101
    KIMCHI_REFRIGERATOR = 102
    ...
Voeg de code voor jouw warmtepomp toe: Scroll naar beneden in die lijst en voeg aan het einde (vlak voor de volgende klasse begint) deze regel toe:

Python
AIR_WATER_HEAT_PUMP = 406
Zorg dat de inspringing (het aantal spaties) exact hetzelfde is als bij de andere regels.

Opslaan: Ctrl+O, Enter, Ctrl+X.
```
